LoginApp/urls.py
from django.urls import path
from . import views

app_name = 'LoginApp'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('sign-in/', views.sign_in, name='signIn'),
    path('sign-out/',views.sign_out, name='sign_out'),
    path('profile/',views.user_profile, name='profile'),
    path('edit-profile/',views.edit_profile, name='edit_profile'),
    path('user-profile/<username>',views.other_users, name='user_profile'),
    path('follow/<username>',views.follow, name='follow'),
    path('un-follow/<username>',views.un_follow, name='un_follow'),
]

MediaNest/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.conf import settings
from PostApp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('LoginApp.urls')),
    path('', include('PostApp.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PostApp/urls.py
from django.contrib import admin
from django.urls import path,include
from PostApp import views

app_name = 'PostApp'

urlpatterns = [
   path('', views.home, name="home"),
   path('liked/<pk>/', views.liked, name='liked'),
   path('un-liked/<pk>/', views.un_liked, name='un_liked')
]

PostApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    caption = models.TextField(max_length=264, blank=True)
    image = models.ImageField(upload_to='post_images')
    upload_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering=['-upload_date']

class Like(models.Model):
    post =  models.ForeignKey(Post, on_delete=models.CASCADE, related_name='liked_post')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker')
    date_created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.user, self.post}'

PostApp/forms.py
from django import forms
from .models import Post
class PostForm(forms.ModelForm):
    caption = forms.CharField(label="", widget=forms.Textarea(attrs={
        'style':'height:90px'
    }))
    
    image = forms.ImageField(label="", widget=forms.ClearableFileInput(attrs={
        'class': 'mb-2',
    }))
    class Meta:
        model = Post
        fields = ['caption', 'image',]
        

PostApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from LoginApp.models import UserProfile, Follow
from PostApp.models import Post, Like
from .forms import PostForm
# Create your views here.
@login_required
def home(request):
    form = PostForm()
    results = None  # Initialize results as None to control display in the template

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('PostApp:home')
    
    if request.method == "GET":
        search = request.GET.get('search', '').strip()
        if search: 
            results = UserProfile.objects.filter(full_name__contains=search).select_related('user')
    
    # Step 1: Get the list of users the current user is following
    following_user_ids = Follow.objects.filter(follower=request.user).values_list('following', flat=True)

    # Step 2: Query posts authored by any user in the `following_user_ids` list
    posts = Post.objects.filter(author__in=following_user_ids).select_related('author').order_by('-upload_date')

    liked_post = Like.objects.filter(user=request.user)
    like_post_list = liked_post.values_list('post', flat=True)
    print(like_post_list)
    
    return render(request, 'PostApp/home.html', context={'form': form, 'results': results, 'posts':posts, 'like_post_list':like_post_list})


@login_required
def liked(request, pk):
    post = Post.objects.get(pk=pk)
    already_liked = Like.objects.filter(post=post, user=request.user)
    
    if not already_liked: 
        liked_post = Like(post=post, user=request.user)
        liked_post.save()
    return redirect('PostApp:home')
    
def un_liked(request, pk):
    post = Post.objects.get(pk=pk)
    already_liked = Like.objects.filter(post=post, user=request.user)
    already_liked.delete()
    return redirect('PostApp:home')

 

templates/PostApp/home.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title %}
  MediaNest
{% endblock %}
{% block body %}
  {% if results %}
    <div class="container mt-5">
      <div class="row">
        {% for result in results %}
          <div class="col-8 m-auto">
        
            <div class="row mb-2 p-2 border ">
              <div class="col-1">
                {% if result.profile_pic %}
                  <img src="/media/{{ result.profile_pic }}" alt="" height="50px" width="50px" class="rounded-circle border border-2 border-success" />
                {% else %}
                  <img src="/media/default_profile.jpg" alt="" height="50px" width="50px" class="rounded-circle border border-2 border-success" />
                {% endif %}
              </div>
              <div class="col-6">
                   <p class="m-0 d-inline-block"><a href="{% url "LoginApp:user_profile" username=result.user.username %}" class="text-decoration-none text-success">@{{ result.user.username }}</a></p>
                   <br>
                   <p class="m-0  d-inline-block">{{result.full_name}}</p>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  {% else %}
    <div class="container mt-4">
      <div class="row">
        <div class="col-7 m-auto">
          <textarea type="button" data-bs-toggle="modal" data-bs-target="#exampleModal" class="rounded rounded-2" style="width: 100%; height: 70px; resize: none;" name="" id=""></textarea>
          <!-- Modal -->
          <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h1 class="modal-title fs-5" id="exampleModalLabel">Create Post</h1>
                </div>
                <div class="modal-body m-0">
                  <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form | crispy}}
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
       
      </div>
    </div>
    <br>
    <hr>
    <br>
    <div class="container">
      <div class="row">
        <div class="col-6 m-auto">
          {% for post in posts %}
            <div class="border border-2 mb-3">
              <div class="p-3 pb-0">
                  <h5 class="m-0"><b>{{ post.author.user_profile.full_name }}</b></h5>
                  <p style="font-size: 12px; m-0">{{ post.upload_date }}</p>
              </div>
              <img class="rounded-0 border mb-2" style="width: 100%;height: 100%;" src="/media/{{ post.image }}" class="card-img-top" alt="..." />
              <h6 class="m-0 mt-1 mb-3 ps-2">{{ post.caption }}</h6>
              <div class="">
                <hr class="mb-2 opacity-10">
                {% if post.pk not in like_post_list %}
                  <p class="text-center m-0"><a href="{% url "PostApp:liked" pk=post.pk %}"><i class="fa-regular fa-heart mb-2 fs-4"></i></a></p>
                {% else %}
                  <p class="text-center m-0"><a href="{% url "PostApp:un_liked" pk=post.pk %}"><i class="fa-solid fa-heart fs-4 mb-1 text-danger"></i></a></p>
                {% endif %}
                <p class="text-center m-0 mb-2" style="font-size: 12px;">{{post.liked_post.count}} Like</p>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}