LoginApp/urls.py
from django.urls import path
from . import views

app_name = 'LoginApp'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('sign-in/', views.sign_in, name='signIn'),
    path('sign-out/',views.sign_out, name='sign_out'),
    path('profile/',views.user_profile, name='profile'),
    path('edit-profile/',views.edit_profile, name='edit_profile'),
    path('user-profile/<username>',views.other_users, name='user_profile'),
    path('follow/<username>',views.follow, name='follow'),
    path('un-follow/<username>',views.un_follow, name='un_follow'),
]

MediaNest/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.conf import settings
from PostApp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('LoginApp.urls')),
    path('', include('PostApp.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PostApp/urls.py
from django.contrib import admin
from django.urls import path,include
from PostApp import views

app_name = 'PostApp'

urlpatterns = [
   path('', views.home, name="home"),
   path('liked/<pk>/', views.liked, name='liked'),
   path('un-liked/<pk>/', views.un_liked, name='un_liked')
]

LoginApp/models.py
from django.db import models
from django.contrib.auth.models import User

from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    full_name = models.CharField(max_length=100)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True, null=True)
    dob = models.DateField(blank=False, null=False)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=False)
    website = models.URLField(blank=True, null=True)
    facebook = models.URLField(blank=True, null=True)
    x = models.URLField(blank=True, null=True)
    description = models.TextField(max_length=350, blank=True)
    
    def __str__(self):
        return f"{self.user.username}'s Profile"

class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    following =  models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created_date = models.DateTimeField(auto_now_add=True)
    

LoginApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import UserProfile  # Import the UserProfile model


class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True, label="", widget=forms.EmailInput(attrs={
        'placeholder': "Email"
    }))
    
    username = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={
        'placeholder': "Username"
    }))
    
    full_name = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={
        'placeholder': "Full Name"
    }))

    password1 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={
        'placeholder': "Password"
    }))
   
    password2 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={
        'placeholder': "Confirm Password"
    }))

    # Additional fields
    dob = forms.DateField(required=True, label="", widget=forms.DateInput(attrs={
        'type': 'date',
        'placeholder': "Date of Birth"
    }))
    
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
    ]
    gender = forms.ChoiceField(required=True, choices=GENDER_CHOICES, label="", widget=forms.Select(attrs={
        'placeholder': "Gender"
    }))

    class Meta:
        model = User
        fields = ('full_name', 'email', 'username', 'password1', 'password2', 'dob', 'gender')

    def save(self, commit=True):
        # Save the User instance first
        user = super().save(commit=commit)
        
        # Save the profile fields
        full_name = self.cleaned_data.get('full_name')
        dob = self.cleaned_data.get('dob')
        gender = self.cleaned_data.get('gender')
        

        # Create or update the UserProfile instance
        UserProfile.objects.update_or_create(
            user=user,
            defaults={'full_name':full_name, 'dob': dob, 'gender': gender}
        )
        
        return user

class EditProfile(forms.ModelForm):
    description = forms.CharField(required=True, widget=forms.Textarea(attrs={
        'style':'height:120px',
        'label':""
    }))
    class Meta:
        model = UserProfile
        exclude = ('user',)

LoginApp/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from .forms import CreateNewUser, AuthenticationForm, EditProfile
from .models import UserProfile, Follow
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from PostApp.forms import PostForm
from django.contrib.auth.models import User

# Create your views here.

def signup(request):
    if request.user.is_authenticated:
        return redirect('PostApp:home')
    
    form = CreateNewUser()
    registered = False    

    if request.method == "POST":
        form = CreateNewUser(data=request.POST)
        
        if form.is_valid():
            form.save()
            registered = True
            return redirect('LoginApp:signIn')
    return render(request, 'LoginApp/signup.html', context={'form': form, 'registered': registered})
  

def sign_in(request):
    
    if request.user.is_authenticated:
        return redirect('PostApp:home')
    
    form = AuthenticationForm()
    
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            
            if user is not None:
                login(request, user)
                return redirect('PostApp:home')
    context = {'form':form}
    return render(request, 'LoginApp/signIn.html', context)

@login_required
def sign_out(request):
    logout(request)
    return redirect('LoginApp:signIn')

@login_required
def user_profile(request):
    user_details =  request.user.user_profile
    
    form = PostForm()
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        
        if form.is_valid():
            print("Done")
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            
            return redirect('LoginApp:profile')

    user_data = User.objects.select_related('user_profile').prefetch_related('post').get(pk=request.user.pk)
    user_posts = user_data.post.all()  # Retrieve all posts related to the user
    user_profile = user_data.user_profile  # Access the user’s profile directly

    
    context = {
        'form':form,
        'user_profile':user_profile,
        'user_posts': user_posts
    }
    return render(request, 'LoginApp/user.html', context=context)


@login_required
def edit_profile(request):
    current_user = UserProfile.objects.get(user=request.user)
    form = EditProfile(instance=current_user)
    
    if request.method == "POST":
        form = EditProfile(request.POST, request.FILES, instance=current_user)
        
        if form.is_valid():
            form.save()
            form = EditProfile(instance=current_user)
            return redirect("LoginApp:profile")
    
    return render(request, 'LoginApp/profile.html', context={'form':form})


@login_required
def other_users(request, username):
    other_user = User.objects.get(username=username)

    already_followed = Follow.objects.filter(follower=request.user, following=other_user)
    
    if other_user == request.user:
        return redirect('LoginApp:profile')
    
    user_profile = UserProfile.objects.select_related('user').get(user__username=username)
    return render(request, 'LoginApp/other_user.html', context={'user_profile': user_profile, 'already_followed':already_followed} )

@login_required
def follow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    
    already_followed = Follow.objects.filter(follower=follower_user, following= following_user)
    
    if not already_followed:
        follow_user = Follow(follower=follower_user, following= following_user)
        follow_user.save()
    return redirect("LoginApp:user_profile", username)

@login_required
def un_follow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following= following_user)
    already_followed.delete()
    return redirect("LoginApp:user_profile", username)

templates/LoginApp/other_user.html
{% extends 'navbar.html' %}
{% load custom_tags %}
{% load crispy_forms_tags %}
{% block title %}
  {{ user_profile.full_name }}(@{{ user_profile.user.username }})
{% endblock %}
{% block body %}
  <div class="container">
    <div class="row mt-5">
      <div class="col-4">
        <img width="250px" height="250px" class="border border-4 border-success rounded-circle" src="/media/{{user_profile.profile_pic|default_profile_pic }}" alt="User Profile Picture" />
      </div>
      <div class="col-6">
        {% if not already_followed %}
            <h3>{{ user_profile.user.username }}&nbsp; <a href="{% url 'LoginApp:follow' username=user_profile.user.username %}" class="btn btn-success btn-sm">Follow</a></h3>
        {% else %}
            <h3>{{ user_profile.user.username }}&nbsp; <a href="{% url 'LoginApp:un_follow' username=user_profile.user.username %}" class="btn btn-success btn-sm">Unfollow</a></h3>
        {% endif %}
       
        <h6>{{ user_profile.user.post.count }} Post &nbsp;|&nbsp; {{ user_profile.user.following.count }} Follower &nbsp;|&nbsp; {{ user_profile.user.follower.count }} Following</h6>
        <br />
        <h4>{{ user_profile.full_name }}</h4>
        <p>{{ user_profile.description }}</p>
        <p>
          <a target="_blank" class="me-2 text-decoration-none text-success" href="{{ user_profile.website }}"><i class="fa-solid fa-globe"></i></a>
          <a target="_blank" class="me-2 text-decoration-none" href="{{ user_profile.facebook }}"><i class="fa-brands fa-facebook"></i></a>
          <a target="_blank" class="text-dark text-decoration-none" href="{{ user_profile.x }}"><i class="fa-brands fa-square-x-twitter"></i></a>
        </p>
      </div>
      {% comment %} <hr class="border-2 border-success" /> {% endcomment %}
    </div>
  </div>
  <br />
  <div class="container">
    <div class="row">
      {% for post in user_profile.user.post.all %}
        <div class="card col-3 p-0 rounded-0">
          {% if forloop.counter < 5 %}
            <img class="rounded-0" style="width: 100%;height: 100%;" src="/media/{{ post.image }}" class="card-img-top" alt="..." />
          {% endif %}
        </div>
      {% endfor %}
    </div>
  </div>
  <br>
  <hr />
  <br />
  <div class="container">
    <div class="row">
      <div class="col-6 m-auto">
        {% for post in user_profile.user.post.all %}
          <div class="border border-2 mb-3">
            <div class="p-3 pb-0">
                <h5 class="m-0"><b>{{ user_profile.full_name }}</b></h5>
                <p style="font-size: 12px; m-0">{{ post.upload_date }}</p>
            </div>
            <img class="rounded-0 border mb-2" style="width: 100%;height: 100%;" src="/media/{{ post.image }}" class="card-img-top" alt="..." />
            <h6 class="m-0 mt-1 mb-3 ps-2">{{ post.caption }}</h6>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

templates/LoginApp/profile.html
{% extends "navbar.html" %}
{% load crispy_forms_tags %}
{% block title %}Edit Profile(@{{user.username}}){% endblock title %}

{% block body %}
    <div class="container">
        <div class="row my-5">
           <div class="col-8 mx-auto">
                <form method="POST", enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form | crispy}}
                    <button type="submit" class="btn btn-success mt-2">Update Profile</button>
                </form>
           </div>
        </div>
    </div>
{% endblock body %}

templates/LoginApp/signIn.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}SignUp{% endblock title %}


{% block body %}
    <div class="container my-4 w-100">
        <div class="row">
            <div class="col-5 m-auto">
                <h3 class="text-center mb-3 logo text-success">MediaNest</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-5 p-3 m-auto shadow border border-1 rounded rounded-1">
                <form method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
            
                    <button type="submit" class="btn btn-success btn w-100">Sign Up</button>
                </form>
            </div>
        </div>
        <div class="row mt-3 text-center">
            <div class="col-5 p-3 m-auto shadow border border-1 rounded rounded-1">
                <p class="m-0"><a href="{% url "LoginApp:signup" %}" class="text-decoration-none text-success">Don't have an account?</a></p>
            </div>
        </div>
    </div>
{% endblock body %}

templates/LoginApp/user.html
{% extends 'navbar.html' %}
{% load custom_tags %}
{% load crispy_forms_tags %}
{% block title %}
  {{ user_details.full_name }}(@{{ user.username }})
{% endblock %}
{% block body %}
  <div class="container">
    <div class="row mt-5">
      <div class="col-4">
        <img width="250px" height="250px" class="border border-4 border-success rounded-circle" src="/media/{{ user.user_profile.profile_pic|default_profile_pic }}" alt="User Profile Picture" />
      </div>
      <div class="col-6">
        <h3>{{ user.username }}&nbsp; <a href="{% url 'LoginApp:edit_profile' %}" class="btn btn-success btn-sm">Edit Profile</a></h3>
        <h6>{{ user.post.count }} Post &nbsp;|&nbsp; {{ user.follower.count }} Followr &nbsp;|&nbsp; {{ user.following.count }} Following</h6>
        <br />
        <h4>{{ user_details.full_name }}</h4>
        <p>{{ user_details.description }}</p>
        <p>
          <a target="_blank" class="me-2 text-decoration-none text-success" href="{{ user_details.website }}"><i class="fa-solid fa-globe"></i></a>
          <a target="_blank" class="me-2 text-decoration-none" href="{{ user_details.facebook }}"><i class="fa-brands fa-facebook"></i></a>
          <a target="_blank" class="text-dark text-decoration-none" href="{{ user_details.x }}"><i class="fa-brands fa-square-x-twitter"></i></a>
        </p>
        <br />
      </div>
      <hr class="border-2 border-success" />
    </div>
  </div>

  <div class="container">
    <div class="row">
      {% for post in user_post.post.all %}
        <div class="card col-3 p-0 rounded-0">
          {% if forloop.counter < 5 %}
            <img class="rounded-0" style="width: 100%;height: 100%;" src="/media/{{ post.image }}" class="card-img-top" alt="..." />
          {% endif %}
        </div>
      {% endfor %}
    </div>
  </div>
  <hr />
  <div class="container mt-4">
    <div class="row">
      <div class="col-7 m-auto">
        <textarea type="button" data-bs-toggle="modal" data-bs-target="#exampleModal" class="rounded rounded-2" style="width: 100%; height: 70px; resize: none;" name="" id=""></textarea>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Create Post</h1>
              </div>
              <div class="modal-body m-0">
                <form method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{ form|crispy }}
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-primary">Save changes</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <hr />

  <div class="container">
    <div class="row">
      <div class="col-6 m-auto">
        {% for post in user_post.post.all %}
          <div class="border border-2 mb-3">
            <div class="p-3 pb-0">
                <h5 class="m-0"><b>{{ user_details.full_name }}</b></h5>
                <p style="font-size: 12px; m-0">{{ post.upload_date }}</p>
            </div>
            <img class="rounded-0 border mb-2" style="width: 100%;height: 100%;" src="/media/{{ post.image }}" class="card-img-top" alt="..." />
            <h6 class="m-0 mt-1 mb-3 ps-2">{{ post.caption }}</h6>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}