LoginApp/urls.py
from django.urls import path
from . import views

app_name = 'LoginApp'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('sign-in/', views.sign_in, name='signIn'),
    path('sign-out/',views.sign_out, name='sign_out'),
    path('profile/',views.user_profile, name='profile'),
    path('edit-profile/',views.edit_profile, name='edit_profile'),
    path('user-profile/<username>',views.other_users, name='user_profile'),
    path('follow/<username>',views.follow, name='follow'),
    path('un-follow/<username>',views.un_follow, name='un_follow'),
]

MediaNest/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.conf import settings
from PostApp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('LoginApp.urls')),
    path('', include('PostApp.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PostApp/urls.py
from django.contrib import admin
from django.urls import path,include
from PostApp import views

app_name = 'PostApp'

urlpatterns = [
   path('', views.home, name="home"),
   path('liked/<pk>/', views.liked, name='liked'),
   path('un-liked/<pk>/', views.un_liked, name='un_liked')
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"/>
    <link href="https://fonts.googleapis.com/css2?family=Agbalumo&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}MediaNest{% endblock title %}</title>
</head>
<body>
    
    {% block body %}{% endblock body %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" />
    <link href="https://fonts.googleapis.com/css2?family=Agbalumo&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>
      {% block title %}
        MediaNest
      {% endblock %}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-success bg-success">
      <div class="container w-100">
        <a class="navbar-brand logo fs-4 text-white" href="{% url 'PostApp:home' %}">MediaNest</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Centered Search Bar -->
          {% comment %} <form class="d-flex mx-auto w-50">
            <input class="form-control me-2 m-auto" type="text" placeholder="Search" />
            <button class="btn btn-primary" type="button">Search</button>
          </form> {% endcomment %}

         {% if request.resolver_match.url_name == 'home' and request.resolver_match.app_name == 'PostApp' %}
                <form class="d-flex mx-auto w-50" method="GET">
                    <input class="form-control me-2 m-auto" style="width: 80%; height: 35px;" type="text" placeholder="Search" name="search" />
                    {% comment %} <button class="btn btn-primary" type="button">Search</button> {% endcomment %}
                </form>
          {% endif %} 

          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {% if user.user_profile.profile_pic %}
                  <img src="/media/{{ user.user_profile.profile_pic }}" alt="" height="40px" width="40px" class="rounded-circle border-white border border-2" />
                {% else %}
                  <img src="/media/default_profile.jpg" alt="" height="40px" width="40px" class="rounded-circle border-white border border-2" />
                {% endif %}
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a class="dropdown-item" href="{% url 'LoginApp:profile' %}">Profile</a>
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'LoginApp:sign_out' %}">Sign Out</a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block body %}
    {% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.bundle.min.js"></script>
  </body>
</html>